### ISSUE TITLE
typo in line 274

### ISSUE THREAD

**Issue by phifedowg** [chris-marsh/fastIPvanish#4]
Hi,

in fastIPvanish script in line 274 you have a typo.
`# Is openvpn installed?
        if ! command_exists "openvpnx" ; then
            error_exit "openvpn does not appear to be installed?"
        fi`

should be openvpn. 

greetings

**Comment by chris-marsh** [comment]
Oops. Thanks.
That was leftover from testing. Changing the command to check was quicker and easier than uninstalling openvpn.
Fixed now.
