### ISSUE TITLE
Updating server list functionality is not working

### ISSUE THREAD

**Issue by tzafarpk** [chris-marsh/fastIPvanish#6]
After updating my Kali linux packages using **`apt-get update`** few days ago, Script stop to update servers list and deleted the **`servers.list`** file. After digging into script **`curl`** command is not retrieving server list and create empty `tmp` file so i modified the script and use the **`wget`** command which is retrieving server list fine.

But these lines of code is not working and not writing **`servers.list`** file with updated servers.

**`function: update_server_list()`**
```bash
# Read and parse results from the temp file
while IFS='' read -r line || [[ -n "$line" ]] ; do
    awk -F'"' '/ipvanish-/{print substr($6, 10, length($6)-14)}' $list \
        >> "$vpn_server_list"
done < "$temp_file"
```

Can you please check if it's working for you or not.

**OS:** Kali Rolling 2019.2
**Awk Version:** GNU Awk 4.2.1, API: 2.0 (GNU MPFR 4.0.2, GNU MP 6.1.2)
**Curl Version:** curl 7.64.0 (Release-Date: 2019-02-06)

**Comment by tzafarpk** [comment]
Change in the line seems to be working for me when using **`wget`** command
**`curl`** command is not working

By replacing **`$6`** with **`$2`**
```
awk -F'"' '/ipvanish-/{print substr($2, 10, length($2)-14)}' $list \
```

**Comment by CoderFromCali** [comment]
The curl command can be fixed by adding `-L` at the beginning.
